version: '1'

services:

    ####################################################################################################
    # PHP
    ####################################################################################################
    php:
        container_name: laravel_php
        build: .docker/php
        ports:
            - "5173:5173"  # Map host port to container port
        volumes:
            - .:/var/www:cached

    ####################################################################################################
    # Nginx
    ####################################################################################################
    nginx:
        container_name: laravel_nginx
        image: nginx
        ports:
            - "81:80"  # Map host port to container port
        volumes:
            - .:/var/www
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php

    ####################################################################################################
    # DATABASE (MySQL)
    ####################################################################################################
    db:
        container_name: laravel_mysql
        image: mysql:8.1
        ports:
            - "3309:3306"  # Map host port to container port
        volumes:
            - .docker/db/data:/var/lib/mysql
            - .docker/logs:/var/log/mysql
            - .docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
            - .docker/db/sql:/docker-entrypoint-initdb.d
        environment:
            MYSQL_DATABASE: laravel_apis
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: root


    ####################################################################################################
    # PHPMyAdmin
    ####################################################################################################
    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"  # Map host port to container port
        environment:
            PMA_HOST: db
            PMA_USER: root
            PMA_PASSWORD: root
        depends_on:
            - db
